version: '3'

services:
    dhcpd:
        container_name: DHCP
        
        image: networkboot/dhcpd
        restart: unless-stopped
        
        volumes:
            - ./dhcpd/data:/data
        
        network_mode: 'host'

        command: enp3s0



    netbootxyz:
        container_name: NetBootXYZ
        
        image: linuxserver/netbootxyz
        restart: unless-stopped
        
    
        volumes:
            - ./netbootxyz/config:/config
            - ./netbootxyz/assets:/assets
        
        environment:
            - PUID=1000
            - PGID=1000
            - PORT_RANGE=30000:30010
            - SUBFOLDER=/
          
        ports:
            - 3000:3000
            - 69:69/udp
            - 8080:80
